version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/AccessAnalytics.Web/clientapp"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/AccessAnalytics.Web"
    schedule: 
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/AccessAnalytics.DataAccess"
    schedule: 
      interval: "monthly"
